#https://stackoverflow.com/questions/44708068/can-ansible-deploy-public-ssh-key-asking-password-only-once?rq=1
#https://aws.amazon.com/blogs/mt/running-ansible-playbooks-using-ec2-systems-manager-run-command-and-state-manager/
- hosts: all
  tasks:
    - authorized_key:
        user: remote_user_name
        state: present
        key: "{{ lookup('file', '/local/path/.ssh/id_rsa.pub') }}"
