---
- hosts: all
  vars:
    users: ['user1', 'user2']
    user_password_valid_max_days: 30 # -1 disables password expiration
  tasks:
    - name: check users password expiration time
      shell: getent shadow "{{ item }}" | cut -d':' -f5
      register: users_pw_valid
      loop: users
      changed_when: False
      check_mode: False
      
    - name: set users password valid time
      shell: chage -M "{{ user_password_valid_max_days }}" "{{ item['item'] }}"
      loop: users_pw_valid.results
      when: item.stdout is defined and item.stdout != {{ user_password_valid_max_days }}
