---
- hosts: all
  gather_facts: false
  name: Gather Cell info & save the data into Cell files.
      
  tasks:
  - name: get cell id info
    raw: shcell
    register: show_cell
  - name: Print the Output
    debug: var=show_cell.stdout_lines   

- hosts: 172.16.3.57
  tasks:
  - name: Copy the show cell result
    copy: src:"{{show_cell.stdout_lines}}" dest:/var/www/html/iperf/cell_result/"{{ansible_hostname}}".txt