#ansible-playbook -i <inventory-file> deploy_authorized_keys.yml --ask-pass --extra-vars='pubkey="<pubkey>"'
#[defaults]
## ansible-playbook -v -b -i /dev/null --check playbook.yml
# ansible-playboook --connection=local --inventory 127.0.0.0.1, playbook.yml
#host_key_checking = False
---
- hosts: all
  tasks:
  - name: Create user - SOME-USER
    user:
      name: acas.user
      password: {{password}}
      #password: "{{ upassword | password_hash('sha512') }}""
      groups:
        - wheel
      state: present

  - name: make diretory 
    file:
      path: "/home/SOME.user/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/SOME.user/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/<username>/.ssh/authorized_keys"
      line: "{{ pubkey }}"
